### ISSUE TITLE
Unable to authenticate into snorby

### ISSUE THREAD

**Issue by enhanced** [djcas9/legacy-snorby#1]
Unable to login, start up snorby, db access etc...  get to login screen a http://address:port use snorby:admin then 500 error, see below output.

=> Booting WEBrick
=> Rails 2.3.2 application starting on http://192.168.1.7:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2009-07-09 11:11:51] INFO  WEBrick 1.3.1
[2009-07-09 11:11:51] INFO  ruby 1.8.6 (2008-08-11) [i386-freebsd7]
[2009-07-09 11:11:51] INFO  WEBrick::HTTPServer#start: pid=91400 port=3000

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 11:12:01) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing ApplicationController#index (for 192.168.1.107 at 2009-07-09 11:12:05) [GET]

ActionController::RoutingError (No route matches "/%5C" with {:method=>:get}):
  /usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/local/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/local/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/local/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:82:in`start'

Rendering /usr/home/jj/Snorby/public/404.html (404 Not Found)

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 11:12:08) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 11:12:13) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)
no

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 11:16:14) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 11:19:37) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 19:17:42) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Redirected to http://192.168.1.7:3000/login
Filter chain halted as [:require_user] rendered_or_redirected.
Completed in 3ms (DB: 0) | 302 Found [http://192.168.1.7/]

Processing UserSessionsController#new (for 192.168.1.107 at 2009-07-09 19:17:42) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
Rendering template within layouts/application
Rendering user_sessions/new
Completed in 70ms (View: 41, DB: 24) | 200 OK [http://192.168.1.7/login]

Processing UserSessionsController#create (for 192.168.1.107 at 2009-07-09 19:17:51) [POST]
  Parameters: {"commit"=>"Login", "user_session"=>{"password"=>"[FILTERED]", "login"=>"snorby", "remember_me"=>"1"}, "action"=>"create", "authenticity_token"=>"jW1QRYoVgxGjue53dsIjivfI7xH4aHNnr0TBc0c3FgE=", "controller"=>"user_sessions"}
Redirected to http://192.168.1.7:3000/
Completed in 368ms (DB: 3) | 302 Found [http://192.168.1.7/user_session]

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 19:17:52) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing PagesController#dashboard (for 192.168.1.107 at 2009-07-09 19:23:21) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}
Rendering template within layouts/application
Rendering pages/dashboard

ActionView::TemplateError (NaN) on line #116 of app/views/pages/dashboard.html.erb:
113:                <td></td>
114:                <td></td>
115:                <td></td>
116:                <td><%= horizontal_bar_graph  [["Event Percentage", ((0 + Event.find(:all, :include => :sig, :conditions => ['signature.sig_class_id = 0']).size/Event.all.size.to_f) \* 100).round(2)]] %></td>
117:                </tr>
118:                <%- for c in @categories -%>
119:                <tr class="<%= cycle('even', 'odd') %>">

```
app/views/pages/dashboard.html.erb:116
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing UserSessionsController#new (for 192.168.1.107 at 2009-07-09 19:23:40) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
Redirected to http://192.168.1.7:3000/account
Filter chain halted as [:require_no_user] rendered_or_redirected.
Completed in 10ms (DB: 3) | 302 Found [http://192.168.1.7/login]

Processing UsersController#show (for 192.168.1.107 at 2009-07-09 19:23:40) [GET]
  Parameters: {"action"=>"show", "controller"=>"users"}
Rendering template within layouts/application
Rendering users/show

ActionView::TemplateError (undefined method `login' for nil:NilClass) on line #3 of app/views/users/show.html.erb:
1: <p>
2:   <b>Login:</b>
3:   <%=h @user.login %>
4: </p>
5: 
6: <p>

```
app/views/users/show.html.erb:3
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

Processing UsersController#show (for 192.168.1.107 at 2009-07-09 19:23:43) [GET]
  Parameters: {"action"=>"show", "controller"=>"users"}
Rendering template within layouts/application
Rendering users/show

ActionView::TemplateError (undefined method `login' for nil:NilClass) on line #3 of app/views/users/show.html.erb:
1: <p>
2:   <b>Login:</b>
3:   <%=h @user.login %>
4: </p>
5: 
6: <p>

```
app/views/users/show.html.erb:3
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /usr/home/jj/Snorby/public/500.html (500 Internal Server Error)

**Comment by djcas9** [comment]
This issue has been fixed.
