### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by joeuser** [djcas9/legacy-snorby#10]
I can't login to snorby -- i get invalid username/password.  I think it has something to do with the error I get when I setup the database etc through rake.  fyi rake is new to me.  There aren't any rows in the user table.  This is fedora on 10.

Here is the trace output:

[root@snorby]# rake snorby:setup RAILS_ENV=production --trace

(in /var/www/html/snorby)
*\* Invoke snorby:setup (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute snorby:setup
[~] Setting Up Snorby Database.
*\* Invoke db:drop (first_time)
*\* Invoke db:load_config (first_time)
*\* Invoke rails_env (first_time)
*\* Execute rails_env
*\* Execute db:load_config
*\* Execute db:drop
*\* Invoke db:create (first_time)
*\* Invoke db:load_config 
*\* Execute db:create
*\* Invoke db:migrate (first_time)
*\* Invoke environment 
*\* Execute db:migrate
==  CreateSessions: migrating =================================================
-- create_table(:sessions)
   -> 0.0024s
-- add_index(:sessions, :session_id)
   -> 0.0131s
-- add_index(:sessions, :updated_at)
   -> 0.0036s
==  CreateSessions: migrated (0.0199s) ========================================

==  CreateSettings: migrating =================================================
-- create_table(:settings)
   -> 0.0029s
-- execute("Insert into settings (app_name, app_dev, app_website, device_name, events_per_page) Values ('Snorby', 'Dustin Willis Webber', 

'http://www.snorby.org', 'Snorby', '20')")
   -> 0.0005s
==  CreateSettings: migrated (0.0038s) ========================================

==  CreateSearches: migrating =================================================
-- create_table(:searches)
   -> 0.0036s
-- add_index(:searches, :sid)
   -> 0.0036s
-- add_index(:searches, :sid_class_id)
   -> 0.0081s
-- add_index(:searches, :ip_src)
   -> 0.0039s
-- add_index(:searches, :ip_dst)
   -> 0.0122s
-- add_index(:searches, :sport)
   -> 0.0047s
-- add_index(:searches, :dport)
   -> 0.0117s
-- add_index(:searches, :sig_priority)
   -> 0.0102s
==  CreateSearches: migrated (0.0601s) ========================================

==  CreateUsers: migrating ====================================================
-- create_table(:users)
   -> 0.0124s
-- add_column(:users, :avatar_file_name, :string)
   -> 0.0181s
-- add_column(:users, :avatar_content_type, :string)
   -> 0.0046s
-- add_column(:users, :avatar_file_size, :integer)
   -> 0.0119s
-- add_column(:users, :avatar_updated_at, :datetime)
   -> 0.0041s
-- add_index(:users, :name)
   -> 0.0041s
-- add_index(:users, :email)
   -> 0.0184s
-- add_index(:users, :persistence_token)
   -> 0.0067s
-- add_index(:users, :last_request_at)
   -> 0.0047s
==  CreateUsers: migrated (0.0872s) ===========================================

==  CreateReports: migrating ==================================================
-- create_table(:reports)
   -> 0.0030s
==  CreateReports: migrated (0.0032s) =========================================

==  CreateCalcCaches: migrating ===============================================
-- create_table(:calc_caches)
   -> 0.0140s
==  CreateCalcCaches: migrated (0.0143s) ======================================

==  CreateImportances: migrating ==============================================
-- create_table(:importances)
   -> 0.0025s
-- add_index(:importances, :sid)
   -> 0.0035s
-- add_index(:importances, :cid)
   -> 0.0036s
-- add_index(:importances, :user_id)
   -> 0.0151s
==  CreateImportances: migrated (0.0256s) =====================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0025s
-- add_index(:comments, :sid)
   -> 0.0040s
-- add_index(:comments, :cid)
   -> 0.0036s
-- add_index(:comments, :user_id)
   -> 0.0130s
==  CreateComments: migrated (0.0240s) ========================================

*\* Invoke db:schema:dump (first_time)
*\* Invoke environment 
*\* Execute db:schema:dump
[~] Importing snort DB schema...
*\* Invoke snorby:cache (first_time)
*\* Invoke environment 
*\* Execute snorby:cache

---
## Building Snorby Cache

[~] Cache Built Successfully.
rake aborted!
undefined method `cid' for nil:NilClass
/var/www/html/snorby/app/models/calc_cache.rb:28:in`build_cache'
/var/www/html/snorby/lib/tasks/install_snorby.rake:110
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/var/www/html/snorby/lib/tasks/install_snorby.rake:14
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

[root@snorby]# rake snorby:cache RAILS_ENV=production
(in /var/www/html/snorby)

---
## Building Snorby Cache

[~] Cache Built Successfully.

---

Snorby Cache Complete!

```
Snorby will cache every hour and clicking the refresh icon on the dashboard will force cache updates.
Some cache updates may take awhile before data changes can be observed.
```

Here are the versions:

[root@snorby]# gem list -l

**\* LOCAL GEMS ***

actionmailer (2.3.4, 2.1.1)
actionpack (2.3.4, 2.1.1)
activeldap (1.2.0, 1.0.9)
activerecord (2.3.4, 2.1.1)
activeresource (2.3.4, 2.1.1)
activesupport (2.3.4, 2.1.1)
arrayfields (4.7.4, 4.5.0)
attributes (5.0.1)
builder (2.1.2)
cgi_multipart_eof_fix (2.5.0, 2.3)
cobbler (1.6.0)
daemons (1.0.10, 1.0.7)
dbd-mysql (0.4.3)
dbi (0.4.3)
deprecated (2.0.1)
facets (2.7.0, 2.5.0)
fastthread (1.0.7, 1.0.1)
fattr (2.1.0)
ferret (0.11.6)
gem2rpm (0.6.0)
gem_plugin (0.2.3)
gettext (2.0.4, 1.93.0)
gettext_activerecord (2.0.4)
git (1.2.5, 1.0.7)
gruff (0.3.6, 0.3.4)
highline (1.5.1, 1.4.0)
hoe (2.3.3, 2.0.0)
hpricot (0.8.1)
htmlentities (4.2.0, 4.0.0)
json_pure (1.1.9)
krb5-auth (0.7)
locale (2.0.4)
main (4.2.0, 2.8.2)
markaby (0.5)
mechanize (0.9.3, 0.9.2)
mongrel (1.1.5, 1.0.1)
mysql (2.8.1)
nokogiri (1.4.0, 1.2.3)
passenger (2.2.5)
pervasives (1.1.0)
picnic (0.8.1.1, 0.6.5)
prawn (0.5.1)
prawn-core (0.5.1)
prawn-format (0.2.1)
prawn-layout (0.2.1)
rack (1.0.1, 0.4.0)
rails (2.3.4, 2.1.1)
rake (0.8.7, 0.8.4)
restr (0.5.2, 0.4.0)
reststop (0.4.1, 0.3.0)
rspec (1.2.9, 1.1.11)
rubyforge (2.0.3, 1.0.3)
rubygems-update (1.3.5, 1.3.4)
sqlite3-ruby (1.2.5, 1.2.4)
tlsmail (0.0.1)
zoom (0.4.1)

[root@snorby]# rake -V
rake, version 0.8.7

[root@snorby]# ruby -v
ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-linux]

[root@snorby]# rails -v
Rails 2.3.4

/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf -f snort.u2 -d /data/snortlogs/ -L /data/snortlogs/ -w /data/snortlogs/barnyard2.waldo -D

/usr/bin/ruby /var/www/html/snorby/script/server -e production -p 48620 -d

**Comment by joeuser** [comment]
the snorby database does update through barnyard...

**Comment by joeuser** [comment]
any ideas?

**Comment by djcas9** [comment]
joeuser,

Drop the database and import the snort mysql schema and then try: rake db:migrate RAILS_ENV=production
then: rake snorby:cache RAILS_ENV=production && rake snorby:cronjob RAILS_ENV=production

Let me know if this fixes the issue also which version of snorby are you using?

Best Regards,

Dustin

**Comment by joeuser** [comment]
On the login screen it says Snorby 2.0.0.  What is the proper way in import the snort/mysql schema?  Thanks for your help, will try shortly...

**Comment by joeuser** [comment]
Still unable to login....  There still is no row in the user table.  The migrate function seems to have completed without any errors, but I am getting the same error on the cache function, and the cronjob function seems to have silently failed.  Relevant output is below:

[root@snort snort-2.8.5.1]# 
[root@snort snort-2.8.5.1]# echo "CREATE DATABASE snorby;" | mysql -u root -p
Enter password: 

[root@snort snort-2.8.5.1]# 
[root@snort snort-2.8.5.1]# echo "grant INSERT,SELECT on snorby.\* to snorby@localhost;" | mysql -u root -p
Enter password: 

[root@snort snort-2.8.5.1]# 
[root@snort snort-2.8.5.1]#  mysql -D snorby -u root -p < ./schemas/create_mysql
Enter password: 

[root@snort snort-2.8.5.1]# 
[root@snort snort-2.8.5.1]# echo "grant INSERT,SELECT,UPDATE on snorby.sensor to snorby@localhost;" | mysql -u root -p
Enter password: 

[root@snort snort-2.8.5.1]# 
[root@snort snort-2.8.5.1]# cd /var/www/html/snorby/

[root@snort snorby]# 
[root@snort snorby]# rake db:migrate RAILS_ENV=production
(in /var/www/html/snorby)
==  CreateSessions: migrating =================================================
-- create_table(:sessions)
   -> 0.0023s
-- add_index(:sessions, :session_id)
   -> 0.0032s
-- add_index(:sessions, :updated_at)
   -> 0.0117s
==  CreateSessions: migrated (0.0179s) ========================================

==  CreateSettings: migrating =================================================
-- create_table(:settings)
   -> 0.0028s
-- execute("Insert into settings (app_name, app_dev, app_website, device_name, events_per_page) Values ('Snorby', 'Dustin Willis Webber', 'http://www.snorby.org', 'Snorby', '20')")
   -> 0.0004s
==  CreateSettings: migrated (0.0036s) ========================================

==  CreateSearches: migrating =================================================
-- create_table(:searches)
   -> 0.0031s
-- add_index(:searches, :sid)
   -> 0.0035s
-- add_index(:searches, :sid_class_id)
   -> 0.0121s
-- add_index(:searches, :ip_src)
   -> 0.0097s
-- add_index(:searches, :ip_dst)
   -> 0.0041s
-- add_index(:searches, :sport)
   -> 0.0129s
-- add_index(:searches, :dport)
   -> 0.0067s
-- add_index(:searches, :sig_priority)
   -> 0.0085s
==  CreateSearches: migrated (0.0621s) ========================================

==  CreateUsers: migrating ====================================================
-- create_table(:users)
   -> 0.0463s
-- add_column(:users, :avatar_file_name, :string)
   -> 0.0038s
-- add_column(:users, :avatar_content_type, :string)
   -> 0.0321s
-- add_column(:users, :avatar_file_size, :integer)
   -> 0.0038s
-- add_column(:users, :avatar_updated_at, :datetime)
   -> 0.0057s
-- add_index(:users, :name)
   -> 0.0036s
-- add_index(:users, :email)
   -> 0.0040s
-- add_index(:users, :persistence_token)
   -> 0.0096s
-- add_index(:users, :last_request_at)
   -> 0.0068s
==  CreateUsers: migrated (0.1175s) ===========================================

==  CreateReports: migrating ==================================================
-- create_table(:reports)
   -> 0.0028s
==  CreateReports: migrated (0.0030s) =========================================

==  CreateCalcCaches: migrating ===============================================
-- create_table(:calc_caches)
   -> 0.0027s
==  CreateCalcCaches: migrated (0.0029s) ======================================

==  CreateImportances: migrating ==============================================
-- create_table(:importances)
   -> 0.0024s
-- add_index(:importances, :sid)
   -> 0.0124s
-- add_index(:importances, :cid)
   -> 0.0035s
-- add_index(:importances, :user_id)
   -> 0.0034s
==  CreateImportances: migrated (0.0224s) =====================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0025s
-- add_index(:comments, :sid)
   -> 0.0035s
-- add_index(:comments, :cid)
   -> 0.0035s
-- add_index(:comments, :user_id)
   -> 0.0074s
==  CreateComments: migrated (0.0177s) ========================================

[root@snort snorby]# 
[root@snort snorby]# rake snorby:cache RAILS_ENV=production && rake snorby:cronjob RAILS_ENV=production
(in /var/www/html/snorby)

---

## Building Snorby Cache

[~] Cache Built Successfully.
rake aborted!
undefined method `cid' for nil:NilClass

(See full trace by running task with --trace)

[root@snort snorby]# 
[root@snort snorby]# rake snorby:cache RAILS_ENV=production --trace
(in /var/www/html/snorby)
*\* Invoke snorby:cache (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute snorby:cache

---

## Building Snorby Cache

[~] Cache Built Successfully.
rake aborted!
undefined method `cid' for nil:NilClass
/var/www/html/snorby/app/models/calc_cache.rb:28:in`build_cache'
/var/www/html/snorby/lib/tasks/install_snorby.rake:110
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

[root@snort snorby]# 
[root@snort snorby]# rake snorby:cronjob RAILS_ENV=production
(in /var/www/html/snorby)

---

## Snorby Cronjob Update

[~] Installing/Updating Snorby Cron Jobs.

---

Snorby Update Complete!

```
If The cronjobs are not being installed or listed with 'crontab -l'
Please install: sudo gem install javan-whenever 
```

[root@snort snorby]# 
[root@snort snorby]# crontab -l
50 14 \* \* \* /etc/webmin/cron/tempdelete.pl
@daily /etc/webmin/time/sync.pl

[root@snort snorby]# 
[root@snort snorby]#  gem install javan-whenever
ERROR:  could not find gem javan-whenever locally or in a repository

[root@snort snorby]# 
[root@snort snorby]#  gem install javan*
ERROR:  could not find gem javan\* locally or in a repository

**Comment by djcas9** [comment]
This issue is caused by empty event tables in the database. I need to fix the cache code to accept nil event counts as a possible option. I would suggest pulling from master until 2.0 is fully completed as there are a number of issues with the dashboard at this point. Development is coming a long great and should be just a few more days until its completion.

**Comment by joeuser** [comment]
Where do I download the master?  Been using BASE for years, I can wait a few days if needed... thanks again

**Comment by djcas9** [comment]
joeuser,
git clone git@github.com:mephux/Snorby.git master
or
git clone git@github.com:mephux/Snorby.git stable

**Comment by joeuser** [comment]
I get -- ERROR: Permission to mephux/Snorby denied to joeuser.
Do I need a paid account to download?

**Comment by djcas9** [comment]
Sorry about that...

git clone git://github.com/mephux/Snorby.git
or
git clone git://github.com/mephux/Snorby.git stable

**Comment by joeuser** [comment]
worked thanks!
