### ISSUE TITLE
smtp issue

### ISSUE THREAD

**Issue by alekm** [djcas9/legacy-snorby#2]
Not sure if i'm missing something.  In email.yml, I've tried "authentication: none" and "authentication: plain".  My smtp server does not require any authentication, it doesn't relay non-local addresses.

with ":authentication: plain" set:

 /usr/src/Snorby/script/runner -e production "Event.run_daily_report"

output:
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48: /usr/lib/ruby/1.8/net/smtp.rb:577:in `auth_plain': 504 5.7.4 Unrecognized authentication type. (Net::SMTPAuthenticationError)
        from /usr/lib/ruby/1.8/net/smtp.rb:571:in`**send**'
        from /usr/lib/ruby/1.8/net/smtp.rb:571:in `authenticate'
        from /usr/lib/ruby/gems/1.8/gems/ambethia-smtp-tls-1.1.2/lib/smtp-tls.rb:32:in`do_start'
        from /usr/lib/ruby/1.8/net/smtp.rb:378:in `start'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:681:in`perform_delivery_smtp'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:523:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:523:in`deliver!'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:395:in `method_missing'
        from /usr/src/Snorby/app/models/event.rb:37:in`run_daily_report'
        from (eval):1
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `eval'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/src/Snorby/script/runner:3

with "authentication: none"

/usr/src/Snorby/script/runner -e production "Event.run_daily_report"

output:
/usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48: /usr/lib/ruby/1.8/net/smtp.rb:566:in `check_auth_args': wrong auth type none (ArgumentError)
        from /usr/lib/ruby/gems/1.8/gems/ambethia-smtp-tls-1.1.2/lib/smtp-tls.rb:12:in`do_start'
        from /usr/lib/ruby/1.8/net/smtp.rb:378:in `start'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:681:in`perform_delivery_smtp'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:523:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:523:in`deliver!'
        from /usr/lib/ruby/gems/1.8/gems/actionmailer-2.3.2/lib/action_mailer/base.rb:395:in `method_missing'
        from /usr/src/Snorby/app/models/event.rb:37:in`run_daily_report'
        from (eval):1
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `eval'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/src/Snorby/script/runner:3

**Comment by djcas9** [comment]
just remove the authentication line. Make sure you have 

:domain: something

**Comment by alekm** [comment]
worked beautifully.  thanks.
