### ISSUE TITLE
Unique Event Type Drill Down Option?

### ISSUE THREAD

**Issue by ghost** [djcas9/legacy-snorby#20]
Is it possible to have a drill-down option to list the "Unique Event Types" shown on the Dashboard screen?  As it stands presently, under Snorby v1.1.3, I am not able to see a list that shows all unique event types.

**Comment by djcas9** [comment]
Good idea, I will be pushing this ability into 2.0 - Thanks JasonLink.

**Comment by ghost** [comment]
You are welcome.  I've used other front-ends in the past and found it useful.  Granted, I am not saying Snorby needs to mimic all features of other solutions - just that some features were useful.  Hope this all helps.
- Jason
