### ISSUE TITLE
snorby 2.0 create pdf: logo not found

### ISSUE THREAD

**Issue by andreshans** [djcas9/legacy-snorby#26]
Error Message: 
ActionView::TemplateError ( not found) on line #23 of app/views/events/show.pdf.prawn:
20: ### Start Of Cover
21: 
22: pdf.move_down(90)
23: pdf.image snorby_logo, :scale => 0.7, :position => :center
24: pdf.move_down(15)
25: pdf.text "#{@event.sig.sig_name}", :size => 15, :style => :bold, :align => :center
26: pdf.text "This report was generated: #{Time.now.strftime('%A, %B %d, %Y')}", :size => 12, :align => :center

**Comment by andreshans** [comment]
Solution:
in app/views/events/show.pdf.prawn
replace the line #13: snorby_logo = "#{Setting.first.logo.path(:large)}"
with: snorby_logo = "#{RAILS_ROOT}/public/images/PDF/snorby_logo.png"

**Comment by djcas9** [comment]
@andreshans I think this issue is related to the static image paths described in ticket: #12 - A fix for this issue with be in Snorby 2.0.
