### ISSUE TITLE
Can't view the dashboard

### ISSUE THREAD

**Issue by jgardner** [djcas9/legacy-snorby#4]
## On OpenBSD 4.5, running snorby 1.1.0

When I go to look at the dashboard, it says 

" We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly."

---

I am running the webrick in non-daemon mode -- errors go to stdout -- and it says this:

Processing PagesController#dashboard (for 10.10.117.9 at 2009-08-14 15:43:58) [GET]
  Parameters: {"action"=>"dashboard", "controller"=>"pages"}

NoMethodError (undefined method `high_severity' for nil:NilClass):
  app/controllers/pages_controller.rb:27:in`dashboard'
  /usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/local/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/local/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/local/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/local/lib/ruby/1.8/webrick/server.rb:82:in`start'

Rendering template within layouts/application
Rendering /errors/500.html.erb (500 Internal Server Error)

**Comment by djcas9** [comment]
Please make sure you created the snorby cache. 'rake snorby:cache RAILS_ENV=production'

**Comment by jgardner** [comment]
That fixed it - thank you!
