### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by pablouesc** [djcas9/legacy-snorby#5]
When I try read/access one item of events I got the message: "We're sorry, but something went wrong." 

the url (example) -> http://x.x.x.x:3000/events/1,19

And there is the log generate:
"ActionView::TemplateError (undefined method `interface' for nil:NilClass) on line #16 of app/views/events/_summary.html.erb:
13:                     </tr>
14:                     <tr>
15:                             <td><%= @event.sensor.id %></td>
16:                             <td><%= @event.sensor.interface %></td>
17:                             <td><%= @event.sensor.hostname %></td>
18:                             <%- if @event.sig.sig_gid == 1 -%>
19:                             <td><%= link_to "#{@event.sig.sig_gid}:#{@event.sig.sig_sid}", "http://rootedyour.com/snortsid?sid=#{@event.sig.sig_sid}", :target => '_blank', :title => 'More Information', :class => 'add_tipsy' %></td>

```
app/views/events/_summary.html.erb:16
app/views/events/show.html.erb:27
app/controllers/events_controller.rb:16:in `show'"
```

I'm using Fedora 10 Linux, rubygems 1.3.1, ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-linux], Rails 2.3.2.

**Comment by pablouesc** [comment]
I'm using Mongrel as http server btw!  ;-)

**Comment by Ticiane** [comment]
Hi! I'm having the same problem! in addition i've got this one: 

ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --with-mysql-config=/usr/bin/mysql_config

after trying to install mysql with gem command

**Comment by pablouesc** [comment]
well... the first problem can be resolved if you configure correctly the snort sensor. The second one, my guess, is trying to install some package (or some packageS or ) of development tools (gcc, automake, g++....) like the build-essential meta-package for Debian and Debian-derivated distributions. Remember... you also need to install mysql client, libraries and etc.

;-)

**Comment by djcas9** [comment]
Should I close this issue or is there still an issue? btw, thank you for posting bugs it really helps in the dev area. Thanks guys..

**Comment by pablouesc** [comment]
Actually, if you change the message "Something went wrong" by something like that: "you need to set up a snort sensor" or if you add a topic at the wiki talking about this (some topic called Troubleshooting for example) help to new users adopt Snorby.

You are welcome. xD

**Comment by pablouesc** [comment]
@Ticiane.... to resolve your problem with fedora, you need run "yum groupinstall 'Development Tools' " ;-)

**Comment by dajackman** [comment]
I had this problem until it add the snortdb-extras tables to the database.
