### ISSUE TITLE
Snorby 1.1.3: Critical Issue

### ISSUE THREAD

**Issue by engineersaeed** [djcas9/legacy-snorby#50]
Hi Folks,

It is my first post here and i just installed the Snorby on a Physical machine from the .iso file.

Now its working fine but how to create/define the category under the Event Category Information.

Regards,

Saeed

**Comment by djcas9** [comment]
@engineersaeed this repo is for legacy Snorby. Please use this repository for the latest release of Snorby. https://github.com/Snorby/snorby or http://snorby.org -- current version is 2.3.12

**Comment by engineersaeed** [comment]
Is this 2.3.12 is .iso file and where is the url for download.

Also same setup as was for the previous version that i installed?

Also 2.3.12 is only IDS or IDS/IPS?

Saeed
