### ISSUE TITLE
Warning Message

### ISSUE THREAD

**Issue by pablouesc** [djcas9/legacy-snorby#6]
Processing EventsController#index (for x.x.x.x at 2009-09-30 12:20:55) [GET]
  Parameters: {"action"=>"index", "controller"=>"events"}
Rendering template within layouts/application
Rendering events/index
Completed in 347ms (View: 283, DB: 17) | 200 OK [http://x.x.x.x/events]
_/root/Snorby/app/views/events/_event.html.erb:53: warning: Object#id will be deprecated; use Object#object_id_

**Comment by djcas9** [comment]
Thank you for posting - This issue is fixed in the next version of snorby.
